const menu = [
  {
    id: 1,
    title: 'makanan carbonara',
    category: 'makanan',
    price: 50000,
    img: './images/food_carbonara.jpg',
    desc: `carbonara ini enak lho`,
  },
  {
    id: 2,
    title: 'minuman boba',
    category: 'milkshake',
    price: 20000,
    img: './images/drink_boba.jpg',
    desc: `minuman dengan boba enak lho`,
  },
  {
    id: 3,
    title: 'Dalgona kopi',
    category: 'kopi',
    price: 30000,
    img: './images/coffee_dalgona.jpeg',
    desc: `anda ngantuk? cobain dalgona nih`,
  },
  {
    id: 4,
    title: 'kentang goreng',
    category: 'makanan',
    price: 10000,
    img: './images/food_kentang.jpg',
    desc: `kentang ini enak lho`,
  },
  {
    id: 5,
    title: 'minuman caramel',
    category: 'milkshake',
    price: 16000,
    img: './images/drink_caramel.jpeg',
    desc: `minuman caramel enak lho`,
  },
  {
    id: 6,
    title: 'Kopi Amerika',
    category: 'kopi',
    price: 25000,
    img: './images/coffee_americano.jpeg',
    desc: `anda ngantuk? cobain kopi amerika nih`,
  },
  {
    id: 7,
    title: 'pizza',
    category: 'makanan',
    price: 25000,
    img: './images/food_pizza.jpg',
    desc: `pizza ini enak lho`,
  },
  {
    id: 8,
    title: 'minuman coklat',
    category: 'milkshake',
    price: 18000,
    img: './images/drink_chocho.jpg',
    desc: `minuman coklat enak lho`,
  },
  {
    id: 9,
    title: 'Ekspresso kopi',
    category: 'kopi',
    price: 32000,
    img: './images/coffee_ekspresso.jpg',
    desc: `anda ngantuk? cobain ekspresso nih`,
  },
  {
    id: 10,
    title: 'sanwich',
    category: 'makanan',
    price: 15000,
    img: './images/food_sanwich.jpg',
    desc: `sanwich ini enak lho`,
  },
  {
    id: 11,
    title: 'strawberry milkshake',
    category: 'milkshake',
    price: 18000,
    img: './images/drink_strawberry.jpg',
    desc: `milkshake strawberry enak lho`,
  },
  {
    id: 12,
    title: 'Kopi Latte',
    category: 'kopi',
    price: 22000,
    img: './images/coffee_latte.jpg',
    desc: `anda ngantuk? cobain kopi latte nih`,
  },
  {
    id: 13,
    title: 'Tuna Oglio',
    category: 'makanan',
    price: 35000,
    img: './images/food_tuna.jpg',
    desc: `Tuna Oglio ini enak lho`,
  },
  {
    id: 14,
    title: 'Milkshake Tarro',
    category: 'milkshake',
    price: 15000,
    img: './images/drink_tarro.jpg',
    desc: `milkshake tarro enak lho`,
  },
  {
    id: 15,
    title: 'Kopi kapucino',
    category: 'kopi',
    price: 20000,
    img: './images/coffee_kapucino.jpg',
    desc: `anda ngantuk? cobain kapucino nih`,
  },
];
export default menu;
